SELECT EMPLOYEE_ID, FIRST_NAME, NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 2)
FROM EMPLOYEES;

SELECT SYSDATE + 12 / 24
FROM DUAL;

SELECT FIRST_NAME, SYSDATE - HIRE_DATE
FROM EMPLOYEES;

SELECT SYSDATE - 3
FROM DUAL;

SELECT SYSDATE + 7
FROM DUAL;

SELECT LAST_DAY('20-SEP-22')
FROM DUAL;

SELECT NEXT_DAY('27-JUL-14', 'SUNDAY')
FROM DUAL;

SELECT NEXT_DAY('27-JUL-14', 1)
FROM DUAL;

SELECT ADD_MONTHS('31-DEC-13', 10)
FROM DUAL;

SELECT NUMTODSINTERVAL(25, 'HOUR'),
NUMTODSINTERVAL(25.4, 'HOUR'),
NUMTODSINTERVAL(25.9, 'HOUR')
FROM DUAL;

SELECT NUMTOYMINTERVAL(11, 'MONTH'),
NUMTOYMINTERVAL(11.4, 'MONTH'),
NUMTOYMINTERVAL(11.5, 'MONTH')
FROM DUAL;

SELECT MONTHS_BETWEEN('31-OCT-14', '31-DEC-13')
FROM DUAL;

SELECT SYSDATE
FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE SOUNDEX(FIRST_NAME) = SOUNDEX('DEN');

SELECT REPLACE('JACK AND JUE', 'J', 'BL')
FROM DUAL;

SELECT TRIM(LEADING 'H' FROM 'HOW ARE YOU DOING ?')
FROM DUAL;

SELECT RPAD(123.456, 10, '*')
FROM DUAL;

SELECT LPAD(123.456, 10, '*')
FROM DUAL;

SELECT INSTR('HELLO', 'E', 1)
FROM DUAL;

SELECT LENGTH('HELLO')
FROM DUAL;

SELECT SUBSTR('HELLO, HOW ARE YOU DOING ?', 1, 5)
FROM DUAL;

SELECT CONCAT('HELLO', 'HOW ARE YOU?')
FROM DUAL;

SELECT INITCAP ('hello')
FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) = 'ROGERS';

SELECT UPPER('hello')
FROM DUAL;

SELECT LOWER('HELLO')
FROM DUAL;

SELECT REMAINDER(11, 3)
FROM DUAL;

SELECT MOD(11, 3)
FROM DUAL;

SELECT FLOOR(2.2345)
FROM DUAL;

SELECT CEIL(2.2345)
FROM DUAL;

SELECT TRUNC(12.345, 2)
FROM DUAL;

SELECT ROUND(12.345, 2)
FROM DUAL;

SELECT FIRST_NAME, LENGTH(FIRST_NAME)
FROM EMPLOYEES;

SELECT employee_id
FROM EMPLOYEES
ORDER BY SALARY DESC
FETCH NEXT 1 PERCENT ROWS ONLY;

SELECT EMPLOYEE_ID
FROM EMPLOYEES
ORDER BY SALARY DESC
FETCH FIRST 3 ROWS ONLY;

SELECT *
FROM (
    SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, (SYSDATE - HIRE_DATE) / 365
    FROM EMPLOYEES
    ORDER BY 4 DESC
)
WHERE ROWNUM <= 6;

SELECT FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, FIRST_NAME, SALARY DESC;

SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY >= 3000
ORDER BY 2, 3 DESC;

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN'
    AND DEPARTMENT_ID = &DEPARTMENT_ID
    AND SALARY > &SALARY;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%SA\_%' ESCAPE '\';

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE (JOB_ID LIKE '%MAN' OR JOB_ID LIKE '%CLERK')
    AND DEPARTMENT_ID = 30
    AND SALARY > 3000;

SELECT FIRST_NAME, LAST_NAME, MANAGER_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE MANAGER_ID IN (101, 104) AND DEPARTMENT_ID IN (100, 110);

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY BETWEEN 11000 AND 12000;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY >= 24000;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE HIRE_DATE = '17-JUN-03';

SELECT 'JOHN IS''NT WORK IN THE DEPARTMENT'
FROM DUAL;

SELECT FIRST_NAME, SALARY, SALARY * 12 + SALARY * 12 * 0.05
FROM EMPLOYEES;

SELECT LAST_NAME, DEPARTMENT_ID, (SALARY + 50) * 12
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12 >= 5;

SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES;

ALTER SESSION SET NLS_LANGUAGE = AMERICAN;
