SELECT employee_id
FROM EMPLOYEES
ORDER BY SALARY DESC
FETCH NEXT 1 PERCENT ROWS ONLY;

SELECT EMPLOYEE_ID
FROM EMPLOYEES
ORDER BY SALARY DESC
FETCH FIRST 3 ROWS ONLY;

SELECT *
FROM (
    SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, (SYSDATE - HIRE_DATE) / 365
    FROM EMPLOYEES
    ORDER BY 4 DESC
)
WHERE ROWNUM <= 6;

SELECT FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, FIRST_NAME, SALARY DESC;

SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY >= 3000
ORDER BY 2, 3 DESC;

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN'
    AND DEPARTMENT_ID = &DEPARTMENT_ID
    AND SALARY > &SALARY;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%SA\_%' ESCAPE '\';

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE (JOB_ID LIKE '%MAN' OR JOB_ID LIKE '%CLERK')
    AND DEPARTMENT_ID = 30
    AND SALARY > 3000;

SELECT FIRST_NAME, LAST_NAME, MANAGER_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE MANAGER_ID IN (101, 104) AND DEPARTMENT_ID IN (100, 110);

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY BETWEEN 11000 AND 12000;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY >= 24000;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE HIRE_DATE = '17-JUN-03';

SELECT 'JOHN IS''NT WORK IN THE DEPARTMENT'
FROM DUAL;

SELECT FIRST_NAME, SALARY, SALARY * 12 + SALARY * 12 * 0.05
FROM EMPLOYEES;

SELECT LAST_NAME, DEPARTMENT_ID, (SALARY + 50) * 12
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12 >= 5;

SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES;

ALTER SESSION SET NLS_LANGUAGE = AMERICAN;
