# docker-compose.yml

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=1234
