# Generated by Django 3.1.2 on 2020-12-05 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountStatus',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('enableFunction', models.TextField(blank=True)),
                ('lastLoginTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='friendInfo',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('friend', models.TextField(blank=True)),
                ('blockade', models.TextField(blank=True)),
                ('pairing', models.TextField(blank=True)),
                ('waiting', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='lifeSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField()),
                ('proportion', models.FloatField()),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='pairingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNum', models.IntegerField()),
                ('locate', models.CharField(max_length=50)),
                ('coordinate', models.CharField(max_length=50)),
                ('userIdA', models.UUIDField()),
                ('userIdB', models.UUIDField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='profilePicture',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='registerInfo',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateTimeField()),
                ('registerTime', models.DateTimeField()),
                ('registerLocate', models.CharField(max_length=50)),
                ('registerCoordinate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('reserveTime', models.DateTimeField()),
                ('reserveLocate', models.CharField(max_length=50)),
                ('reserveCoordinate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('introduction', models.TextField(blank=True)),
                ('interest', models.TextField(blank=True)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('sex', models.BooleanField()),
                ('sexori', models.BooleanField()),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('constellation', models.IntegerField()),
                ('disposition', models.TextField(blank=True)),
                ('matchingAge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='verifyInfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('verifyCode', models.CharField(max_length=6)),
                ('time', models.DateTimeField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
