# Generated by Django 3.1.2 on 2020-12-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verifyInfo',
        ),
    ]
