# Generated by Django 3.1.2 on 2020-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0003_remove_reservation_reservecoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
