# Generated by Django 3.1.2 on 2020-12-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0005_auto_20201215_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='job',
            new_name='school',
        ),
    ]
