# Generated by Django 3.1.2 on 2020-12-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0007_userinfo_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifesharing',
            name='proportion',
        ),
    ]
