# Generated by Django 3.1.2 on 2020-12-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0008_remove_lifesharing_proportion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairingrecord',
            name='serialNum',
        ),
    ]
