# Generated by Django 3.1.2 on 2020-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0011_auto_20201223_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='birthday',
            field=models.DateField(),
        ),
    ]
