# Generated by Django 3.1.2 on 2020-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0013_auto_20201223_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='avatar/')),
            ],
        ),
        migrations.DeleteModel(
            name='profilePhoto',
        ),
    ]
