# Generated by Django 3.1.2 on 2020-12-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0014_auto_20201224_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
