# Generated by Django 3.1.2 on 2020-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0015_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('reserveTime', models.DateTimeField()),
                ('reserveLocate', models.CharField(max_length=10)),
            ],
        ),
    ]
