# Generated by Django 3.1.2 on 2020-12-28 08:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0018_auto_20201228_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='constellation',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='disposition',
            field=django_mysql.models.ListCharField(models.IntegerField(), max_length=30, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='place',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='school',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='birthday',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sex',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sexori',
            field=models.IntegerField(default='-1'),
        ),
    ]
