# Generated by Django 3.1.2 on 2020-12-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0019_auto_20201228_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstatus',
            name='status',
        ),
    ]
