# Generated by Django 3.1.2 on 2020-12-28 09:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0021_auto_20201228_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='disposition',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=25, size=5),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='interest',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[1, 2, 3, 4, 5], max_length=25, size=5),
        ),
    ]
