# Generated by Django 3.1.2 on 2020-12-28 12:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0022_auto_20201228_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='school',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='interest',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], max_length=25, size=5),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
