# Generated by Django 3.1.2 on 2020-12-28 12:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0026_auto_20201228_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='disposition',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=25, size=None),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='interest',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[11, 11, 11, 11, 11], max_length=20, size=None),
        ),
    ]
