# Generated by Django 3.1.2 on 2020-12-28 12:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0030_auto_20201228_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='interest',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[11, 11, 11, 11, 11], max_length=14, size=None),
        ),
    ]
