# Generated by Django 3.1.2 on 2020-12-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0034_auto_20201228_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinginfo',
            old_name='matchingkind',
            new_name='matchingKind',
        ),
    ]
