# Generated by Django 3.1.2 on 2020-12-28 12:58

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0035_auto_20201228_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='enableFunction',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
