# Generated by Django 3.1.2 on 2020-12-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0036_auto_20201228_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='enableFunction',
            field=models.JSONField(default={}),
        ),
    ]
