# Generated by Django 3.1.2 on 2020-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0039_auto_20201228_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifesharing',
            name='num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='lifesharing',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='lifePhotos/'),
        ),
    ]
