# Generated by Django 3.1.2 on 2020-12-31 14:08

from django.db import migrations, models
import gpsDatingApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0040_auto_20201231_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=gpsDatingApp.models.avatar_directory_path),
        ),
    ]
