# Generated by Django 3.1.2 on 2020-12-31 17:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0041_auto_20201231_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='disposition',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sexori',
            field=models.CharField(default='', max_length=10),
        ),
    ]
