# Generated by Django 3.1.2 on 2021-01-02 18:23

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0043_auto_20210101_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='enableFunction',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[], size=None),
        ),
    ]
