# Generated by Django 3.1.2 on 2021-01-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0045_auto_20210103_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='lastJwtRefreshTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000001'),
        ),
    ]
