# Generated by Django 3.1.2 on 2021-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0046_auto_20210103_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='lastJwtRefreshTime',
            field=models.DateTimeField(),
        ),
    ]
