# Generated by Django 3.1.2 on 2021-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0047_auto_20210103_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedinfo',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='lifesharing',
            name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='isRegister',
            field=models.BooleanField(default=True),
        ),
    ]
