# Generated by Django 3.1.2 on 2021-01-08 16:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0049_auto_20210103_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedinfo',
            name='constellation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='interest',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sex',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sexori',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pairingrecord',
            name='locate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='registerLocate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserveLocate',
            field=models.CharField(max_length=50),
        ),
    ]
