# Generated by Django 3.1.2 on 2021-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0051_auto_20210109_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='rolePermission',
            field=models.CharField(default='Guest', max_length=20),
        ),
    ]
