# Generated by Django 3.1.2 on 2021-01-22 16:27

from django.db import migrations, models
import gpsDatingApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0052_basicinfo_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifesharing',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=gpsDatingApp.models.life_sharing_directory_path),
        ),
        migrations.AlterField(
            model_name='lifesharing',
            name='num',
            field=models.IntegerField(),
        ),
    ]
