# Generated by Django 3.1.2 on 2021-01-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0054_lifesharingorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerinfo',
            name='registerCoordinate',
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='registerCoordinateLat',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='registerCoordinateLng',
            field=models.FloatField(default=-1),
        ),
    ]
