# Generated by Django 3.1.2 on 2021-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0056_auto_20210131_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingrecord',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='registerDistrict',
            field=models.CharField(default='', max_length=50),
        ),
    ]
