# Generated by Django 3.1.2 on 2021-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0057_auto_20210131_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='completeQuickSetting',
            field=models.BooleanField(default=False),
        ),
    ]
