# Generated by Django 3.1.2 on 2021-02-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0058_accountstatus_completequicksetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatus',
            old_name='completeQuickSetting',
            new_name='isCompleteQuickSetting',
        ),
    ]
