# Generated by Django 3.1.2 on 2021-02-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0059_auto_20210210_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='sexori',
        ),
    ]
