# Generated by Django 3.1.2 on 2021-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0060_remove_basicinfo_sexori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstatus',
            old_name='isCompleteQuickSetting',
            new_name='isCompleteFirstSetting',
        ),
    ]
