# Generated by Django 3.1.2 on 2021-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0061_auto_20210227_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedinfo',
            old_name='place',
            new_name='city',
        ),
        migrations.AddField(
            model_name='advancedinfo',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
