# Generated by Django 3.1.2 on 2021-03-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0062_auto_20210302_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialinfo',
            old_name='blockade',
            new_name='blockadeList',
        ),
        migrations.RenameField(
            model_name='socialinfo',
            old_name='friend',
            new_name='friendList',
        ),
    ]
