# Generated by Django 3.1.2 on 2021-03-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0063_auto_20210320_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairingrecord',
            name='district',
        ),
        migrations.RemoveField(
            model_name='pairingrecord',
            name='locate',
        ),
    ]
