# Generated by Django 3.1.2 on 2021-05-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0066_auto_20210403_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedinfo',
            name='constellation',
        ),
    ]
