# Generated by Django 3.1.2 on 2021-05-11 12:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0067_remove_advancedinfo_constellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockadeListInfo',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('blockadeList', django_mysql.models.ListTextField(models.CharField(max_length=36), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='friendListInfo',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('friendList', django_mysql.models.ListTextField(models.CharField(max_length=36), default=[], size=None)),
            ],
        ),
    ]
