# Generated by Django 3.1.2 on 2021-05-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0068_blockadelistinfo_friendlistinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialInfo',
        ),
    ]
