# Generated by Django 3.1.2 on 2021-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsDatingApp', '0069_delete_socialinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='rolePermission',
            field=models.CharField(default='', max_length=20),
        ),
    ]
