version: "3.8"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-by-compose
    ports:
      - "8889:8888"
    depends_on:
      - pgvector

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-by-compose
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
