"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

# ==================================================
# ==================================================
# ==================================================
"""
online modify / git push
1. domain suffix
2. debug
3. db
4. static file
5. ASGI
"""
# ==================================================
# ==================================================
# ==================================================

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxx'

# SECURITY WARNING: don't run with debug turned on in production!

# ==================================================

# for runserver
# DOMAIN_SUFFIX = ''

# --------------------------------------------------

# for apache
# DOMAIN_SUFFIX = 'prd/api/'

# ==================================================

# ==================================================

# for runserver
# DEBUG = True

# --------------------------------------------------

# for apache
# DEBUG = False

# ==================================================

# ==================================================

# for test

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',

#     'xxx',
#     'xxx,

#     'xxx',
#     'xxx',
#     'xxx'
# ]

# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1",
#     "http://127.0.0.1:8000",

#     "xxx",
#     "xxx",
#     "xxx",
#     "xxx",

#     "xxx",
#     "xxx",
#     "xxx",
#     "xxx",
# ]

# --------------------------------------------------

# for online

# ALLOWED_HOSTS = [
#     'xxx',
#     'xxx',
#     'xxx'
# ]

# CORS_ALLOWED_ORIGINS = [
#     "xxx",
#     "xxx",
#     "xxx",

#     "xxx",
#     "xxx",
#     "xxx",
# ]

# ==================================================


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gpsDatingApp',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'channels',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# ==================================================

# local mysql
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'gpsdatingapp',
#         'USER': 'root',
#         'PASSWORD': 'xxx',
#         'HOST': 'localhost',
#         'PORT': '',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# --------------------------------------------------

# aws mysql for dev
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dbmaster',
#         'USER': 'dbmasteruser',
#         'PASSWORD': 'xxx',
#         'HOST': 'xxx',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# ==================================================

# aws mysql for prd
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dbmaster',
#         'USER': 'dbmasteruser',
#         'PASSWORD': 'xxx',
#         'HOST': 'xxx',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# ==================================================

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# ==================================================

# for runserver
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# --------------------------------------------------

# for apache
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# ==================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 2 MB
MAX_FILE_SIZE = 2097152

# SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP伺服器
EMAIL_PORT = 587  # TLS通訊埠號
EMAIL_USE_TLS = True  # 開啟TLS(傳輸層安全性)
EMAIL_HOST_USER = 'xxx'  # 寄件者電子郵件
EMAIL_HOST_PASSWORD = 'xxx'  # Gmail應用程式的密碼

# reCAPTCHA
GOOGLE_RECAPTCHA_SECRET_KEY = 'xxx'
GOOGLE_RECAPTCHA_URL = 'https://www.google.com/recaptcha/api/siteverify'

# Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "xxx",
        },
    },
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis://:xxx@127.0.0.1:6379")],
        },
    },
}

# logging
LOGGING = {
    'version': 1,
    'loggers': {
        'chance_logger': {
            'handlers':['file'],
            'level':'DEBUG'    
        }
    },
    'handlers': {
        'file': {
            'level':'DEBUG',
            'class':'logging.FileHandler',
            'filename':'./log.log',
            'formatter':'format',
            'filters': ['require_debug_true'],
            'encoding': 'utf-8'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'format': {
            'format':'{levelname} {asctime} {module} {process:d} {thread:d} {message}',   
            'style': '{',
        }
    }
}

# Google Sign-In
GOOGLE_SIGN_IN_CLIENT_ID = "xxx"

# # SSL
# # secure proxy SSL header and secure cookies
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# # session expire at browser close
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# # wsgi scheme
# os.environ['wsgi.url_scheme'] = 'https'


# ==================================================

# 指定 ASGI 的路由地址
# for runserver
# ASGI_APPLICATION = 'project.routing.application'

# --------------------------------------------------

# 指定 ASGI 的路由地址
# for dephne
# ASGI_APPLICATION = 'project.asgi.application'

# ==================================================
