FROM python:3.8-slim
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple aiohttp
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple aiomysql
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple sqlalchemy
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple aiohttp_jinja2
