#server:
#  port: 8081
#  servlet:
#    session:
#      timeout: 30
#  tomcat:
#    uri-encoding: UTF-8

age: 19
name: zhaodabao

personinfo:
  name: zhaoxiaobao
  age: 3

spring:
  profiles:
    active: dev
