arr: str = [
    "互聯網路 Internetwork",
    "網際網路 Internet",
    "網路設備 Network Device",
    "網路媒介 Network Media",
    "路由器 Router",
    "交換器 Switch",
    "集線器 Hub",
    "有線 Wire",
    "無線 Wireless",
    "銅線 Cable",
    "光纖 Fiber",
    "連接埠 Port",
    "快速乙太網 Faster Ethernet",
    "共享匯流排 Shared Bus",
    "通道 Channel",
    "MAC 位址 Media Access Control Address",
    "區域網路位址 LAN Address",
    "乙太網路位址 Ethernet Address",
    "實體位址 Physical Address",
    "OUI 網路卡製造商編號 Organizationally Unique Identifier",
    "NIC 廠商內控流水號 Network Interface Controller",
    "U / L bit (Universal / Local)",
    "全球唯一 Globally Unique",
    "本地自行管理 Locally Administered",
    "丟棄 Drop",
    "混雜模式 Promiscuous Mode",
    "單播傳送 Unicast",
    "廣播傳送 Broadcast",
    "群播傳送 Multicast",
    "群組 Group",
    "碰撞 Collision",
    "碰撞區域 Collision Domain",
    "載波偵聽多路存取 Carrier Sense Multiple Access",
    "碰撞偵測 Collision Detection",
    "後退演算法 Backoff Algorithm",
    "早期碰撞 Early Collision",
    "晚期碰撞 Late Collision",
    "橋接器 Bridge",
    "記憶體 RAM",
    "駭客 Hacker",
    "灌爆 Overflow",
    "Mac 表洪水攻擊 MAC Address Table Flooding Attack",
    "端口安全 Port - Security",
    "存取控制串列 Access Control List",
    "端口存取控制串列 Port - ACL",
    "動態 Dynamic",
    "靜態 Static",
    "存活時間 Age Time",
    "全雙工 Full Duplex",
    "半雙工 Half Duplex",
    "自動協商 Auto",
    "乙太網路 Ethernet",
    "高速乙太網路 Fast Ethernet",
    "十億位元乙太網路 Gigabit Ethernet",
    "儲存轉送 Store - And - Forward",
    "截穿轉送 Cut - Through",
    "無碎片轉發 Fragment - Free",
    "廣播資料 Broadcast Message",
    "廣播區域 Broadcast Domain",
    "網路區域 Network Segment",
    "繞送 Routing",
    "路由表 Routing Table",
    "預設閘道 Default Gateway",
    "負載平衡 Load Balance",
    "預設閘道備援協定 Gateway Redundant Protocol",
    "熱備份路由器協定 Hot Standby Router Protocol",
    "三層式網路架構 3 - Tier Network Architecture",
    "存取層 Access",
    "分散層 Distribution",
    "核心層 Core",
    "堆疊 Stack",
    "主幹 - 枝葉架構 Spine - Leaf",
    "全網狀連線 Full Mesh",
    "雙絞線 Twisted Pair",
    "無遮蔽式雙絞線 Unshielded Twisted Pair, UTP",
    "遮蔽式雙絞線 Shielded Twisted Pair, STP",
    "電力線網路 Powerline Networking",
    "供電乙太網路 Power Over Ethernet, POE",
    "電源注入器 Power Injector",
    "直線網路線 Straight Through",
    "跳線網路線 Crossover",
    "交叉模式媒體相依介面 Medium Dependent Interface Crossover, MDIX",
    "OSI 實體層 Physical Layer",
    "OSI 資料連結層 Data - Link Layer",
    "OSI 網路層 Network Layer",
    "OSI 傳輸層 Transport Layer",
    "OSI 會議層 Session Layer",
    "OSI 表達層 Presentation Layer",
    "OSI 應用層 Application Layer",
    "DoD 模型 Department Of Defense",
    "TCP / IP 網路存取層 Network Access",
    "TCP / IP 網際網路層 Internet Layer",
    "TCP / IP 傳輸層 Transport Layer",
    "TCP / IP 應用層 Application Layer",
    "表頭檔 Header",
    "封裝 Encapsulation",
    "解封裝 Decapsulation",
    "通訊協定資料單元 PDU, Protocol Data Unit",
    "區段 Segment",
    "封包 Packet",
    "訊框 Frame",
    "網域名稱服務協定 DNS",
    "動態主機 IP 配置協定 DHCP",
    "超文字傳輸協定 HTTP",
    "簡易郵件傳輸協定 SMTP",
    "郵件接收協定 POP",
    "遠端登入協定 Telnet or SSH",
    "檔案傳輸協定 FTP",
    "檔案傳輸協定 TFTP",
    "應用協定編號 Port Number",
]


if __name__ == "__main__":
    if len(set(arr))==len(arr):
        print("OK !")
    else:
        print("GG !")
